### ISSUE TITLE
query function did not work under certain circumstances

### ISSUE THREAD

**Issue by smilefufu** [bdarnell/torndb#32]
as described in title.
code:
```python
names = ['aa', 'bb', 'cc']
db.query("select * from tab_name where name in %s", names)
```
name column is varchar(127)

I check mysql query log, the query that torndb using is:
```sql
select * from tab_name where name in ("'aa'", "'bb'", "'cc'")
```
while the right query should be 
```sql
select * from tab_name where name in ("aa", "bb", "cc")
```

I think it is caused by environment, because the situation happened on two of my computers but not happen on another.

How can I solved this problem?

**Comment by bdarnell** [comment]
Perhaps you have different versions of MySQLdb? It looks like there was a change in version 1.2.5: https://github.com/farcepest/MySQLdb1/commit/87d1145c0d6ee4f5a8ecf6d5c62d2479b9cf27ea

In any case, this looks like it's more likely to be a MySQLdb issue than a torndb issue.

**Comment by smilefufu** [comment]
You're right, I've tested it. It's a MySQLdb issue which happened under and include version 1.2.4.
