### ISSUE TITLE
An important cue    very upset

### ISSUE THREAD

**Issue by huaiguoguo** [bdarnell/torndb#35]
Why don't you update torndb's reference Pack: MySQLdb

Below the python3.4.3 no have MySQLdb, it was renamed to pymysql

I just refer to the torndb No in my project: "module named'MySQLdb'"

Why, I am very, very, very upset, why you don't update, now have a lot of people use python3.4.3

please.............please...............

**Comment by bdarnell** [comment]
As the readme says, this package is no longer actively maintained. It exists for backwards compatibility; new projects should probably choose a different package. Or you're welcome to fork it (under a new name) if you'd like to continue the project.
